### ISSUE TITLE
typo on release title "Release 2022-09-14. Bandwidth enhancements.", should be 2023

### ISSUE THREAD

**Issue by smoy** [steveloughran/cloudstore#5]
Saw the release tag and release title. Release tag is "tag-release-2023-09-14" but the title and release note is 2022. Probably a typo.

https://github.com/steveloughran/cloudstore/releases/tag/tag-release-2023-09-14

**Comment by steveloughran** [comment]
thanks. will fix note. wonder if that's a bug in my typing or the script snippets I use to generate releases (see BUILDING.md)
